# Jykell configuration
#markdown: redcarpet
#highlighter: pygments
markdown: kramdown
highlighter: rouge
paginate: 5
language: 'en-uk
'

# Website info
name: 'Adventures in teach'
description: ""

# Author's info
author: 'Jaqueline Steiger'
# edit 'categories' in the front matter of every post to match this username
nickname: Monk1
bio: 'Complaining and measuring horses. Scolding fish. Normal stuff'
location: 'Thailand'
url: 'http://esimonian.github.io/TEFLBlog/'
image: 'assets/images/jaqlargehead.jpg'

short_url: 'esimonian.github.io/TEFLBlog/'
google_analytics:
disqus: 
# edit baseurl to simply '/' if using as your personal page (instead of a project page)
baseurl: /TEFLBlog/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag


# gems and other configs
gems: [jekyll-paginate]
exclude: [vendor]

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...


# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
safe: false
lsi: false
username: monk1
repo: TEFLBlog
branch: master
relative_source: ../TEFLBlog/
destination: ../TEFLBlog-pages/
production_url:  http://esimonian.github.io/TEFLBlog/
source_url:      https://github.com/esimonian/TEFLBlog/

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
